# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fresh < Formula
  desc "Git repository management CLI tool"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.2.4/fresh_1.2.4_darwin_amd64.tar.gz"
      sha256 "d258b7fd9729cdcddb762f44647f49a24ce8e4599bbaef238b6aa322c04a56cf"

      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.2.4/fresh_1.2.4_darwin_arm64.tar.gz"
      sha256 "c82074276247a53b74b46b72017e45b4d9df035c9789732c3fb05a1c09c42f84"

      def install
        bin.install "fresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.2.4/fresh_1.2.4_linux_amd64.tar.gz"
      sha256 "15de5db3e25faaf935034961cd27d9b3209c7f6005947c2c61a5903ef2e1050d"
      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.2.4/fresh_1.2.4_linux_arm64.tar.gz"
      sha256 "8bdd7604dc7dd9344469e3fa0b31d76909a642f18b7c33fea2820e277f6abdc1"
      def install
        bin.install "fresh"
      end
    end
  end
end
