# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fresh < Formula
  desc "A CLI tool for interactively managing the status of multiple Git repositories"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.9.1/fresh_1.9.1_darwin_amd64.tar.gz"
      sha256 "88e0c4535d52df6981066f19ee7094fbfa7d92827218ceba2d8e378f8eb9e2ed"

      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.9.1/fresh_1.9.1_darwin_arm64.tar.gz"
      sha256 "477f0a899c6c791df047d5740deb5b6fbf95a96116864c8289bd3f8b0a9cfec5"

      def install
        bin.install "fresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.9.1/fresh_1.9.1_linux_amd64.tar.gz"
      sha256 "b109fb60a447776c1e8da421cbaaf3af4f5a0538bcfee5069383b298ecbe8795"
      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.9.1/fresh_1.9.1_linux_arm64.tar.gz"
      sha256 "8f8f143ea31d0794301a0adf0bc7662832570f4a465f836f108011908fac8c0b"
      def install
        bin.install "fresh"
      end
    end
  end
end
