# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fresh < Formula
  desc "Git repository management CLI tool"
  homepage "https://github.com/jsmenzies/fresh"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.7.0/fresh_1.7.0_darwin_amd64.tar.gz"
      sha256 "4364d213946ca894b550f8afc52ce0aa1015036367f8d1e32483411b92d21e9a"

      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.7.0/fresh_1.7.0_darwin_arm64.tar.gz"
      sha256 "c4bb7f428cd8c4ab902c22c3ea7a5f106d4b57de55ac0881ea86bc87a468da51"

      def install
        bin.install "fresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.7.0/fresh_1.7.0_linux_amd64.tar.gz"
      sha256 "f97ad3b93586ad2d826b658254716178419556949d3c427fd19c1c16f4766db4"
      def install
        bin.install "fresh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jsmenzies/fresh/releases/download/v1.7.0/fresh_1.7.0_linux_arm64.tar.gz"
      sha256 "b25a9cf8a7256984588062db07d6570ba613847e469b7bbfc680d6ddf726dea7"
      def install
        bin.install "fresh"
      end
    end
  end
end
